import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GlassNavbar } from "@/components/landing/glassy-navbar";

const bpgGlaho = localFont({
  src: [
    {
      path: "../public/fonts/bpg-glaho/BPGGlaho.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/bpg-glaho/BPGGlaho.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-bpg-glaho",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ka">
      <body className={`${bpgGlaho.variable} font-georgian antialiased`}>
        <div>
          {/* <GlassNavbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
